name: After Deploy Workflow

on:
  workflow_run:
    workflows: ["Deploy action for GCP project"]
    branches: [master, qa, develop]
    types:
      - completed

jobs:
  after_deploy:
    name: After Deploy
    runs-on: ubuntu-latest
    steps:
      #############
      ### SETUP ###
      #############
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: '5.6.5'

      - name: Install git-chglog
        uses: nosportugal/ghaction-install-git-chglog@v1

      ###########
      ### RUN ###
      ###########
      - name: Get Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.10

      - name: Create changelog file
        run: |
          git-chglog -o CHANGELOG.md --next-tag ${{ steps.gitversion.outputs.SemVer }}

      - name: Push changed files to branch
        uses: nosportugal/ghaction-publish-changes@1.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH_NAME: ${{ steps.gitversion.outputs.branchName }}

      - name: Get last sha after the push in the above step
        id: get_last_sha
        run: |
          git fetch
          echo "::set-output name=lastsha::$(git rev-parse HEAD)"

      - name: Create tag
        id: create_tag
        uses: actions/github-script@v4
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.gitversion.outputs.SemVer }}",
              sha: "${{ steps.get_last_sha.outputs.lastsha }}"
            })
